# -*- coding: utf-8 -*-
"""Task2_SKT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VvHoBe_R4l2nZIhVX3Oc9-tJfAWl5Qh
"""

# Task 2: K-Means Clustering - Customer Segmentation
# Machine Learning Internship


# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


# Load Dataset
url = "https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/master/Datasets/Mall_Customers.csv"
data = pd.read_csv(url)

print("Dataset Preview ")
print(data.head(), "\n")

print("Missing Values")
print(data.isnull().sum(), "\n")


# Feature Selection
X = data[['Annual Income (k$)', 'Spending Score (1-100)']]


# Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# Determine Optimal Number of Clusters using Elbow Method
inertia = []
K = range(1, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(7, 4))
plt.plot(K, inertia, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal k')
plt.grid(True)
plt.show()


# Apply K-Means Clustering with Optimal k=5
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
data['Cluster'] = kmeans.fit_predict(X_scaled)


# Cluster Centers (Original Units)
centers = scaler.inverse_transform(kmeans.cluster_centers_)
cluster_summary = pd.DataFrame(centers, columns=['Annual Income (k$)', 'Spending Score (1-100)'])
cluster_summary['Cluster'] = range(0, 5)

print("Cluster Summary")
print(cluster_summary, "\n")


# Visualize Clusters
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=data,
    x='Annual Income (k$)',
    y='Spending Score (1-100)',
    hue='Cluster',
    palette='Set1',
    s=100
)
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, marker='X', label='Centroids')
plt.title('Customer Segments - Income vs Spending')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

"""**Conclusion:**

K-Means clustering segmented customers into 5 distinct groups based on annual income and spending score. These segments reveal clear patterns in customer behavior, which can guide targeted marketing and business strategies.
"""